"""Batch-first medical terminology utilities."""

from .core.config import LOCAL_LITE_MEMORY_PROFILES, LocalLiteConfig, local_lite_config
from .core.models import (
    CodeInfo,
    CodeMapping,
    CodeRef,
    CodeRelation,
    CodeResolution,
    ConceptMapRow,
    FriendlyNameResult,
    NameSearchResult,
    OptimizeResult,
    OptimizeRule,
    Provenance,
    ProvenanceStep,
    SourceStats,
)
from .core.schemas import (
    OUTPUT_SCHEMA_VERSION,
    OutputField,
    OutputSchema,
    get_output_schema,
    list_output_schemas,
)
from .domains import (
    cross_reference,
    diagnosis_codes,
    discover,
    drugs_by_class,
    drugs_for_indication,
    fda_label_by_rxcui,
    guideline_fulltext,
    guideline_recommendations,
    guideline_search,
    guidelines_for_code,
    hcpcs_drugs,
    indication_search,
    lab_codes,
    lab_value_codes,
    procedure_codes,
    search_drug,
    vaccine_codes,
)
from .ds import (
    code_ttys_dataframe,
    conceptmap_dataframe,
    hierarchy_dataframe,
    lookup_dataframe,
    map_dataframe,
    mapping_conceptmap_dataframe,
    patient_friendly_dataframe,
    sample_codes_dataframe,
    search_names_dataframe,
    source_stats_dataframe,
)
from .engines.api import RemoteApiEngine
from .services.bulk import (
    iter_batches,
    iter_hierarchy_bulk,
    iter_lookup_bulk,
    iter_mapping_bulk,
    iter_patient_friendly_bulk,
)
from .services.conceptmap import (
    get_concept_map,
    get_mapping_concept_map,
    iter_concept_map,
    iter_mapping_concept_map,
)
from .services.discovery import get_code_ttys, get_source_stats, sample_source_codes, search_names
from .services.hierarchy import (
    get_ancestors,
    get_children,
    get_code_relations,
    get_descendants,
    get_parents,
)
from .services.lookup import get_code_info, get_code_infos
from .services.mapping import get_code_mappings
from .services.optimize import optimize_codes
from .services.patient_friendly import get_patient_friendly_names
from .services.resolution import resolve_codes

__all__ = [
    "CodeRef",
    "CodeInfo",
    "CodeMapping",
    "CodeRelation",
    "CodeResolution",
    "ConceptMapRow",
    "FriendlyNameResult",
    "NameSearchResult",
    "OptimizeResult",
    "OptimizeRule",
    "LOCAL_LITE_MEMORY_PROFILES",
    "LocalLiteConfig",
    "OUTPUT_SCHEMA_VERSION",
    "OutputField",
    "OutputSchema",
    "Provenance",
    "ProvenanceStep",
    "RemoteApiEngine",
    "SourceStats",
    "code_ttys_dataframe",
    "conceptmap_dataframe",
    "cross_reference",
    "diagnosis_codes",
    "discover",
    "drugs_by_class",
    "drugs_for_indication",
    "fda_label_by_rxcui",
    "get_ancestors",
    "get_children",
    "get_code_relations",
    "get_concept_map",
    "get_code_ttys",
    "get_mapping_concept_map",
    "get_source_stats",
    "get_descendants",
    "get_code_info",
    "get_code_infos",
    "get_code_mappings",
    "optimize_codes",
    "get_output_schema",
    "get_parents",
    "get_patient_friendly_names",
    "guideline_fulltext",
    "guideline_recommendations",
    "guideline_search",
    "guidelines_for_code",
    "hcpcs_drugs",
    "hierarchy_dataframe",
    "indication_search",
    "lab_codes",
    "lab_value_codes",
    "sample_source_codes",
    "lookup_dataframe",
    "map_dataframe",
    "mapping_conceptmap_dataframe",
    "patient_friendly_dataframe",
    "procedure_codes",
    "sample_codes_dataframe",
    "search_drug",
    "search_names_dataframe",
    "search_names",
    "source_stats_dataframe",
    "vaccine_codes",
    "iter_batches",
    "iter_concept_map",
    "iter_hierarchy_bulk",
    "iter_lookup_bulk",
    "iter_mapping_bulk",
    "iter_mapping_concept_map",
    "iter_patient_friendly_bulk",
    "list_output_schemas",
    "local_lite_config",
    "resolve_codes",
]
